bookreview/catalog/urls.py
#Linking to locallibrary/urls.py file

#This is where we'll add our patterns as we build the application

from django.conf.urls import url
from . import views

#^ is a string start marker and $ is an end of string marker
urlpatterns = [
    url(r'^$', views.index, name='index'),       #Will call views.index is pattern is detected
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name="author-detail"),
]

bookreview/locallibrary/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

#Use include() to add URLS from the catalog application
urlpatterns += [
    url(r'^catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

bookreview/catalog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date


# Create your models here.
class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Language(models.Model):
    """
    Model representing the language of the book
    """
    name = models.CharField(max_length=200, help_text="Enter the book's language (e.g., English, Spanish, French, etc.")

    def __str__(self):
        """
        String for representing the Model object
        :return: string
        """
        return self.name


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because Subject can contain many books. Books can cover many subjects.
    # Subject declared as an object because it has already been defined.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    @property
    def is_overdue(self):
        """
        Returns true is book is past due
        :return: bool
        """
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)        #User who borrows book

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='d', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.book.title)


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100, blank=True)          #Author may have middle name/initial
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def get_author_name(self):
        """
        Return the author's complete name for display
        :return: String
        """
        return '%s %s %s' % (self.first_name, self.middle_name, self.last_name)

    def __str__(self):
        """
        String for representing the Model object
        :return: String
        """
        return '%s, %s %s' % (self.last_name, self.first_name, self.middle_name)

bookreview/catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Book, Author, BookInstance, Genre


def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()  # The 'all()' is implied by default.
    num_genres = Genre.objects.count()

    #Number of visits to this view
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_books': num_books, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available, 'num_authors': num_authors,
                 'num_genres': num_genres, 'num_visits' : num_visits},

    )

from django.views import generic

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10
    # context_object_name = 'my_book_list'  # your own name for the list as a template variable
    # queryset = Book.objects.filter(title__icontains='war')[:5]  # Get 5 books containing the title war
    # template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

bookreview/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}
        <title>Local Library</title>
        {% endblock %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!--For additional CSS files-->
        {% load static %}
        <link rel="stylesheet" type= "text/css" href="{% static 'css/styles.css' %}">
    </head>

    <body>
         <div class="container">
             <div class="row">
                 <nav class="navbar navbar-expand-xl navbar-inverse">﻿
                     <div class="container">
                       <button class="navbar-toggler" data-toggle="collapse" data-target="#mainNav">
                         <span class="navbar-toggler-icon">
                         </span>
                       </button>
                       <div class="collapse navbar-collapse" id="#mainNav">
                        <div class="navbar-nav">
                          <a class="btn btn-info" role="button" href="{% url 'index' %}">Home</a>
                          <a class="btn btn-info" role="button" href="{% url 'books' %}">All books</a>
                          <a class="btn btn-info" role="button" href="{% url 'authors' %}">All authors</a>
                            {% if user.is_authenticated %}
                                     <li>User: {{ user.get_username }}</li>
                                     <a class="btn btn-info" role="button" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
                                     {% else %}
                                     <a class="btn btn-info" role="button" href="{% url 'login'%}?next={{request.path}}">Login</a>
                            {% endif %}
                        </div>
                       </div>
                     </div>
                 </nav>

                 <div class="col-sm-10 ">
                 {% block content %}{% endblock %}

                     <!--Handling pagination-->

                     {% block pagination %}
                          {% if is_paginated %}
                              <div class="pagination">
                                  <span class="page-links">
                                      {% if page_obj.has_previous %}
                                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                      {% endif %}
                                      <span class="page-current">
                                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                      </span>
                                      {% if page_obj.has_next %}
                                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                      {% endif %}
                                  </span>
                              </div>
                          {% endif %}
                        {% endblock %}
                 </div>
             </div>
         </div>

    </body>
</html>

bookreview/catalog/templates/catalog/author_detail.html
<!DOCTYPE html>
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.get_author_name }}</h1>



  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    <dl>
        {% for book in author.book_set.all %}
            <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
            <dd><b>({{book.display_genre}})</b> {{book.summary}}</dd>
        {% endfor %}
    </dl>
  </div>
{% endblock %}

bookreview/catalog/templates/catalog/author_list.html
<!DOCTYPE html>
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">
            {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{%endif%})
        </a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}

{% endblock %}

bookreview/catalog/templates/catalog/book_detail.html
<!DOCTYPE html>
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

bookreview/catalog/templates/catalog/book_list.html
<!DOCTYPE html>
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}

{% endblock %}

bookreview/catalog/templates/index.html
<!DOCTYPE html>
{% extends "base_generic.html" %}

{% block content %}
<body class="body-background">

<!--Dynamic content will be items that will be updated-->
<h2><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Online book review</h2>
    <p>The library has the following record counts:</p>
      <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
        <li><strong>Genres:</strong> {{num_genres}}</li>
      </ul>

    <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

</body>
{% endblock %}